### ISSUE TITLE
Get error "Runtime Error"

### ISSUE THREAD

**Issue by shuat** [SteveLTN/https-portal#171]
I am getting the following error:

```
Verifying domain_name ...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 197, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/bin/acme_tiny", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for domain_name: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/qJO4Q5a2r2okJN-vE8xAa9wAw030M22uRQ7NtfVe8p8/193787222', u'token': u's9Onj8ruOGLMm_zhcfr7CK5bLjkBmhN9ZavhEPzsQZ0', u'type': u'tls-alpn-01'}, {u'status': u'invalid', u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/qJO4Q5a2r2okJN-vE8xAa9wAw030M22uRQ7NtfVe8p8/193787223', u'token': u'Eo9eoflid2N8r2hdVYBcdFAW5Hsujt5o4CW03PPh9Qw', u'type': u'dns-01'}, {u'status': u'invalid', u'validationRecord': [{u'url': u'http://domain_name/.well-known/acme-challenge/Qap4mgRhg6S8rkmCltnOrDAQ1PrH_WR9R_7WBK7XTtY', u'hostname': u'domain_name', u'addressUsed': u'2607:f1c0:100f:f000::209', u'port': u'80', u'addressesResolved': [u'xx.101.70.xx, u'2607:f1c0:100f:f000::209']}], u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/qJO4Q5a2r2okJN-vE8xAa9wAw030M22uRQ7NtfVe8p8/193787224', u'token': u'Qap4mgRhg6S8rkmCltnOrDAQ1PrH_WR9R_7WBK7XTtY', u'error': {u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from http://domain_name/.well-known/acme-challenge/Qap4mgRhg6S8rkmCltnOrDAQ1PrH_WR9R_7WBK7XTtY: "<!DOCTYPE html>\\r\\n<html>\\r\\n    <head>\\r\\n        <title>Runtime Error</title>\\r\\n        <meta name=\\"viewport\\" content=\\"width=device-w"'}, u'type': u'http-01'}], u'identifier': {u'type': u'dns', u'value': u'domain_name'}, u'expires': u'2018-11-16T13:56:59Z'}
```

when I go to http://domain_name/.well-known/acme-challenge/Qap4mgRhg6S8rkmCltnOrDAQ1PrH_WR9R_7WBK7XTtY it downloads a file with some random key. 
The only thing I can think of is I am using floating IPs from digital ocean. They point to my server and I am able to get to my server. Does that cause issues?

**Comment by shuat** [comment]
I am able to get to my server. I am using GoDaddy which points to Digital Ocean floating IP (their version of static IP) which points to my server. I have docker swarm setup. I used this library dozens of times and it usually works. I really appreciate your dedication to this project!.

**Comment by SteveLTN** [comment]
If you are able to get the random string at the acme-challenge path, then it shouldn't throw this error.

Is it possible that you can access the server by the domain but let's encrypt's servers can't?

**Comment by shuat** [comment]
@SteveLTN No reason that I can think of. I posted with all the domain info. When I click on the link it triggers a download with that random string.

```
Starting crond ...
2018/11/09 23:14:32 [crit] 213#213: *51 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 10.255.0.2, server: 0.0.0.0:443
2018/11/10 03:08:54 [crit] 213#213: *314 SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking, client: 10.255.0.2, server: 0.0.0.0:443
Renewing ...
Renewal skipped for godaven-prod.bitbean.com, it expires at 89 days from now.
Signing certificates from https://acme-staging-v02.api.letsencrypt.org/directory ...
Parsing account key...
Parsing CSR...
Found domains: beta.godaven.com
Getting directory...
Directory found!
Registering account...
Already registered!
Creating new order...
Order created!
Verifying beta.godaven.com...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 197, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 193, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/bin/acme_tiny", line 149, in get_crt
    raise ValueError("Challenge did not pass for {0}: {1}".format(domain, authorization))
ValueError: Challenge did not pass for beta.godaven.com: {u'status': u'invalid', u'challenges': [{u'status': u'invalid', u'validationRecord': [{u'url': u'http://beta.godaven.com/.well-known/acme-challenge/qDV28LQPlNQTnuhH0S3jBvqaAigDmjCL_IlHXYhc_Aw', u'hostname': u'beta.godaven.com', u'addressUsed': u'2607:f1c0:100f:f000::209', u'port': u'80', u'addressesResolved': [u'104.248.252.84', u'2607:f1c0:100f:f000::209']}], u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Wt5YlrTTHPGVsXyxKWWsDG3SC9JVc_c2fRtUhQ38790/194072662', u'token': u'qDV28LQPlNQTnuhH0S3jBvqaAigDmjCL_IlHXYhc_Aw', u'error': {u'status': 403, u'type': u'urn:ietf:params:acme:error:unauthorized', u'detail': u'Invalid response from http://beta.godaven.com/.well-known/acme-challenge/qDV28LQPlNQTnuhH0S3jBvqaAigDmjCL_IlHXYhc_Aw: "<!DOCTYPE html>\\r\\n<html>\\r\\n    <head>\\r\\n        <title>Runtime Error</title>\\r\\n        <meta name=\\"viewport\\" content=\\"width=device-w"'}, u'type': u'http-01'}, {u'status': u'invalid', u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Wt5YlrTTHPGVsXyxKWWsDG3SC9JVc_c2fRtUhQ38790/194072663', u'token': u'sTI-gTIag3w3f32QMe1s54w0BbNQgeIvckAqydniU18', u'type': u'dns-01'}, {u'status': u'invalid', u'url': u'https://acme-staging-v02.api.letsencrypt.org/acme/challenge/Wt5YlrTTHPGVsXyxKWWsDG3SC9JVc_c2fRtUhQ38790/194072664', u'token': u'46wXzBP9bDhXEY6BpK8hk3gtur5BWXAnp0yyGY9_1tw', u'type': u'tls-alpn-01'}], u'identifier': {u'type': u'dns', u'value': u'beta.godaven.com'}, u'expires': u'2018-11-17T07:42:02Z'}
```

**Comment by SteveLTN** [comment]
You can run commands to do it, but I doubt that you are going to have any different messages.

```
        acme_tiny \
          --account-key /var/lib/https-portal/account.key \
          --csr #{domain.csr_path} \
          --acme-dir /var/www/default/challenges/ \
          --disable-check \
          --directory-url 'https://acme-staging-v02.api.letsencrypt.org/directory' > #{domain.ongoing_cert_path}
``` 

This is the command you need. The directory names don't really matter, but you need to find the CSR path. It's in `/var/lib/https-portal/#{domain_name}/#{stage}/domain.csr`. 

Still, I think the reason is LE servers not being able to access your server. IP restrictions etc. maybe?

**Comment by shuat** [comment]
@SteveLTN Thanks for that update. Did not have a chance to test. However as you can see from my snippet above the API was able to get a cert for godaven-prod.bitbean.com just not for beta.godaven.com

**Comment by SteveLTN** [comment]
Yes, I noticed that. It is really weird.

**Comment by SteveLTN** [comment]
Closing due to inactivity.
