### ISSUE TITLE
Cannot Generate Certificates On Mac in https-portal 1.18.0

### ISSUE THREAD

**Issue by eligundry** [SteveLTN/https-portal#273]
Hi there, one of the developers on my team started getting errors in the 1.18 release. We reverted their https portal image to 1.17 and that fixed the issue. They are using Docker for Mac 3.1.0.

```
/opt/certs_manager/lib/open_ssl.rb:58:in `system': no implicit conversion of Integer into String (TypeError)
         from /opt/certs_manager/lib/open_ssl.rb:58:in `self_sign'
        from /opt/certs_manager/lib/acme.rb:9:in `sign'
        from /opt/certs_manager/certs_manager.rb:116:in `block in ensure_signed'
         from /opt/certs_manager/certs_manager.rb:111:in `each'
         from /opt/certs_manager/certs_manager.rb:111:in `ensure_signed'
         from /opt/certs_manager/certs_manager.rb:46:in `block in setup_config'
         from /opt/certs_manager/certs_manager.rb:133:in `block in with_lock'
        from /opt/certs_manager/certs_manager.rb:131:in `open'
         from /opt/certs_manager/certs_manager.rb:131:in `with_lock'
         from /opt/certs_manager/certs_manager.rb:19:in `setup_config'
         from /opt/certs_manager/certs_manager.rb:11:in `setup'
         from /bin/setup:4:in `<main>'
[cont-init.d] 20-setup: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
proxy exited with code 1
```

**Comment by SteveLTN** [comment]
May I have your docker-compose file?
