### ISSUE TITLE
502 Bad Gateway error

### ISSUE THREAD

**Issue by aforty** [SteveLTN/https-portal#37]
I assume this is a temporary lets encrypt problem but wanted to make you aware anyway. I'm getting this for all my domains and as a result none of my servers are accessible. Is there any way to use previous certificates in case of failure like this so that servers can at least remain accessible?

```
2016/04/04 17:20:39 [notice] 122#122: signal process started
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 198, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 85, in get_crt
    "agreement": "https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf",
  File "/bin/acme_tiny", line 47, in _send_signed_request
    protected["nonce"] = urlopen(CA + "/directory").headers['Replay-Nonce']
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway
Failed to obtain certs for __my_domain__.com
```

**Comment by aforty** [comment]
And yeah I accidentally had FORCE_RENEW enabled, but still would be nice if certificate renewal failure didn't take down the server. Let me know if I can help with any additional info!

**Comment by SteveLTN** [comment]
Hmm, it makes sense if the failure doesn't take down the server. I'll have a look when I have time.

**Comment by SteveLTN** [comment]
@aforty Hi, sorry that I didn't got time till now. In which form did the failed renew take down the server?

**Comment by SteveLTN** [comment]
I believe this is solved. Please pull  the latest image.
