### ISSUE TITLE
Vhost not working after failed cert renew attempt

### ISSUE THREAD

**Issue by OndroNR** [SteveLTN/https-portal#56]
We have problem with non working virtual host entry after failed certificate renewal attempt. After failed renewal, vhost configuration was still set to acme challenge while certificate was still valid. We also had previous DNS problem, which probably triggered this behaviour. We changed certificate time to live threshold from 30 days to 10 days as quick workaround.

Log:

```
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain1.com...
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
  File "/bin/acme_tiny", line 104, in get_crt
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 194, in main
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 198, in <module>
Traceback (most recent call last):
  "status": 429
  "detail": "Error creating new authz :: Too many currently pending authorizations.",
  "type": "urn:acme:error:rateLimited",
ValueError: Error requesting challenges: 429 {
}
Failed to obtain certs for domain1.com
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain2.com...
  "status": 429
  "detail": "Error creating new authz :: Too many currently pending authorizations.",
  "type": "urn:acme:error:rateLimited",
ValueError: Error requesting challenges: 429 {
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
  File "/bin/acme_tiny", line 104, in get_crt
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 194, in main
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 198, in <module>
Traceback (most recent call last):
}
Failed to obtain certs for domain2.com
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain3.com...
================================================================================
Failed to sign domain3.com, is DNS set up properly?
================================================================================
Failed to obtain certs for domain3.com
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain4.com...
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
  File "/bin/acme_tiny", line 104, in get_crt
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 194, in main
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 198, in <module>
Traceback (most recent call last):
  "status": 429
  "detail": "Error creating new authz :: Too many currently pending authorizations.",
  "type": "urn:acme:error:rateLimited",
ValueError: Error requesting challenges: 429 {
}
Failed to obtain certs for domain4.com
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Already registered!
Verifying domain5.com...
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
  File "/bin/acme_tiny", line 104, in get_crt
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 194, in main
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 198, in <module>
Traceback (most recent call last):
  "status": 429
  "detail": "Error creating new authz :: Too many currently pending authorizations.",
  "type": "urn:acme:error:rateLimited",
ValueError: Error requesting challenges: 429 {
}
Failed to obtain certs for domain5.com
[cont-init.d] 00-setup: exited 0.
[cont-init.d] 10-set-docker-gen-status: executing...
[cont-init.d] done.
[cont-init.d] 10-set-docker-gen-status: exited 0.
[services.d] starting services
[services.d] done.
Starting crond ...
ValueError: Error requesting challenges: 503 <HTML><HEAD>
<TITLE>Service Unavailable</TITLE>
</HEAD><BODY>
    raise ValueError("Error requesting challenges: {0} {1}".format(code, result))
  File "/bin/acme_tiny", line 104, in get_crt
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 194, in main
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 198, in <module>
Traceback (most recent call last):
Reference&#32;&#35;15&#46;57f01202&#46;1468846508&#46;b73b83e
The server is temporarily unable to service your request.  Please try again
<H1>Service Unavailable - Zero size object</H1>
later.<P>
</BODY></HTML>
```

**Comment by SteveLTN** [comment]
Can you elaborate it a bit more about the following?
> After failed renewal, vhost configuration was still set to acme challenge while certificate was still valid. 

A renewal failed. Then what did you expect, and what actually happened?

**Comment by OndroNR** [comment]
A expected it to use certificate which was still valid for 30 more days. Instead, nginx vhost conf contained this https://github.com/SteveLTN/https-portal/blob/master/fs_overlay/var/lib/nginx-conf/default.conf.erb . Attempt to access https://hostname fell back to default nginx vhost (implemented in our fork).

**Comment by SteveLTN** [comment]
For each site, there will be two files for nginx conf (a `.conf` and a `.ssl.conf`). It is completely normal to have the content of `default.conf.erb` there. The acme challenge config will always be there, and it also redirects the request to https.

I think the problem is that when an exception happens, I print the message then the renewal flow continues, which leads to a reload of Nginx with a wrong certs. Now I use a temporary file to save the on-going certs then replace it with the old one when it succeeds. This should solve the problem.
