### ISSUE TITLE
Cannot download acme-challenge 

### ISSUE THREAD

**Issue by lucj** [SteveLTN/https-portal#60]
Hi, 

I've setup https-portal in a service of my compose file but got the following error during startup.

```
2016/08/19 13:02:38 [notice] 135#135: signal process started
Generating RSA private key, 2048 bit long modulus
...............................+++
...........................................................................................+++
e is 65537 (0x10001)
Signing certificates from https://acme-v01.api.letsencrypt.org ...
Parsing account key...
Parsing CSR...
Registering account...
Registered!
Verifying www.mydomain.com...
Traceback (most recent call last):
  File "/bin/acme_tiny", line 198, in <module>
    main(sys.argv[1:])
  File "/bin/acme_tiny", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "/bin/acme_tiny", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /var/www/default/challenges/YCKUvZB8pEbmRGMNyQvUIDcFOifPoVecry7hN01FpfI, but couldn't download http://www.mydomain.com/.well-known/acme-challenge/YCKUvZB8pEbmRGMNyQvUIDcFOifPoVecry7hN01FpfI
2016/08/19 13:02:39 [emerg] 151#151: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mydomain.com/production/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mydomain.com/production/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
Signed key for www.mydomain.com
2016/08/19 13:02:39 [emerg] 152#152: SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mydomain.com/production/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/https-portal/www.mydomain.com/production/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)
Generating RSA private key, 2048 bit long modulus
......................................................................+++
...............................................................+++
```

In my compose file, I have

```
# TLS termination
  tls:
    image: steveltn/https-portal
    environment:
      - 'DOMAINS=www.mydomain.com -> http://proxy, admin.mydomain.com -> http://proxy:8000, api.mydomain.com -> http://proxy:8080'
      - 'FORCE_RENEW=true'
      - 'STAGE=production'
    links:
      - proxy
    ports:
      - '80:80'
      - '443:443'
    restart: always
```

The Docker host is behind a router configured to forward incoming traffic on port 80 and 443.
Any idea ?

**Comment by SteveLTN** [comment]
Most likely your DNS is not set up properly.

**Comment by lucj** [comment]
Hum, that is strange as the DNS seems fine though (replaced my real domain with mydomain.com)

; <<>> DiG 9.10.3-P4-Ubuntu <<>> www.mydomain.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1775
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.mydomain.com.			IN	A

;; ANSWER SECTION:
www.mydomain.com.		18723	IN	CNAME	mydomain.com.
mydomain.com.		18723	IN	A	XX.XXX.XXX.XXX    //  -> Correct ip of the server

;; Query time: 26 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Fri Aug 19 17:08:23 CEST 2016
;; MSG SIZE  rcvd: 71

**Comment by lucj** [comment]
I've created the cname entries yesterday, might be due to dns propagation...

**Comment by lucj** [comment]
I was too much in a hurry...seems dns is done now. Working like a charm.
Thanks a lot, this is a great and useful image.
