### ISSUE TITLE
Agreement URL problem during startup

### ISSUE THREAD

**Issue by pumox** [SteveLTN/https-portal#61]
Hi, I have a problem during startup of the container. It tells me that the agreement URL is invalid. Could you please help?

2016-08-19 18:28:45	stdout	Failed to obtain certs for jiratest.obeznani.pl
2016-08-19 18:28:45	stdout	}
2016-08-19 18:28:45	stdout	  "status": 400
2016-08-19 18:28:45	stdout	  "**detail": "Provided agreement URL [https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf] does not match current agreement URL [https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]",**
2016-08-19 18:28:45	stdout	  "type": "urn:acme:error:malformed",
2016-08-19 18:28:45	stdout	ValueError: Error registering: 400 {
2016-08-19 18:28:45	stdout	    raise ValueError("Error registering: {0} {1}".format(code, result))
2016-08-19 18:28:45	stdout	  File "/bin/acme_tiny", line 92, in get_crt
2016-08-19 18:28:45	stdout	    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
2016-08-19 18:28:45	stdout	  File "/bin/acme_tiny", line 194, in main
2016-08-19 18:28:45	stdout	    main(sys.argv[1:])
2016-08-19 18:28:45	stdout	  File "/bin/acme_tiny", line 198, in <module>
2016-08-19 18:28:45	stdout	Traceback (most recent call last):
2016-08-19 18:28:44	stdout	Registering account...
2016-08-19 18:28:44	stdout	Parsing CSR...
2016-08-19 18:28:44	stdout	Parsing account key...
2016-08-19 18:28:44	stdout	Signing certificates from https://acme-v01.api.letsencrypt.org ...
2016-08-19 18:28:44	stdout	e is 65537 (0x10001)
2016-08-19 18:28:44	stdout	.........................+++
2016-08-19 18:28:44	stdout	.+++
2016-08-19 18:28:44	stdout	Generating RSA private key, 2048 bit long modulus
2016-08-19 18:28:44	stdout	2016/08/19 18:28:44 [notice] 129#129: signal process started
2016-08-19 18:28:43	stdout	e is 65537 (0x10001)
2016-08-19 18:28:43	stdout	..................++
2016-08-19 18:28:43	stdout	..............................................................++
2016-08-19 18:28:41	stdout	Generating RSA private key, 4096 bit long modulus
2016-08-19 18:28:41	stdout	...
2016-08-19 18:24:30	stdout	This is going to take a long time
2016-08-19 18:24:30	stdout	Generating DH parameters, 2048 bit long safe prime, generator 2
2016-08-19 18:24:29	stdout	[cont-init.d] 00-setup: executing... 
2016-08-19 18:24:29	stdout	[cont-init.d] executing container initialization scripts...
2016-08-19 18:24:29	stdout	[fix-attrs.d] done.
2016-08-19 18:24:29	stdout	[fix-attrs.d] 00-runscripts: exited 0.
2016-08-19 18:24:29	stdout	[fix-attrs.d] 00-runscripts: applying... 
2016-08-19 18:24:29	stdout	[fix-attrs.d] applying owners & permissions fixes...

**Comment by SteveLTN** [comment]
I guess I need to update acme-tiny.py.

I'm currently on vacation now. Might have a look later.

**Comment by pumox** [comment]
That would be great, because with the current docker image it's not possible to setup any website :)

**Comment by SteveLTN** [comment]
I updated it. Update the image and Try again please.

**Comment by vespakoen** [comment]
The image is not pushed to docker hub yet =(

**Comment by SteveLTN** [comment]
I'll have a look tonight.

**Comment by SteveLTN** [comment]
I'm sure this time I pushed.

**Comment by SteveLTN** [comment]
@vespakoen Please have a look.

**Comment by vespakoen** [comment]
Looking good =)

"Last pushed: 2 days ago"

This can be closed
