### ISSUE TITLE
Fail at signing domain

### ISSUE THREAD

**Issue by sbehrends** [SteveLTN/https-portal#68]
I have a docker http working and I wanted to add a Let's Encrypt certificate for SSL.
While setting it up using docker-compose I run with this problem.

FYI: Port 80 is being used by this docker-compose. And DNS is setup correctly, if I use local environment (self signed certificate) domain works properly.
```
tcp6       0      0 :::80                   :::*                    LISTEN      11945/docker-proxy
```

docker-compose.yml
```
version: '2'
services:
  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      DOMAINS: 'git.mydomain.co -> http://dockerhost:10080'
      STAGE: 'production'
    volumes:
      - ./ssl_certs:/var/lib/https-portal
```

Any thoughts?

```
https-portal_1  | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1  | [fix-attrs.d] 00-runscripts: applying...
https-portal_1  | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-setup: executing...
https-portal_1  | 2016/11/02 12:14:43 [notice] 123#123: signal process started
https-portal_1  | Signing certificates from https://acme-v01.api.letsencrypt.org ...
https-portal_1  | Parsing account key...
https-portal_1  | Parsing CSR...
https-portal_1  | Registering account...
https-portal_1  | Already registered!
https-portal_1  | Verifying git.mydomain.co...
https-portal_1  | /opt/certs_manager/lib/acme.rb:28:in `system': execution expired (Timeout::Error)
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:28:in `block in le_sign'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:16:in `le_sign'
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:9:in `sign'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:60:in `block in ensure_signed'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:53:in `each'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:53:in `ensure_signed'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:19:in `setup'
https-portal_1  |   from /etc/cont-init.d/00-setup:4:in `<main>'
https-portal_1  | ================================================================================
https-portal_1  | Failed to sign git.mydomain.co, is DNS set up properly?
https-portal_1  | ================================================================================
https-portal_1  | [cont-init.d] 00-setup: exited 1.
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: executing...
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 12:15:13 [emerg] 164#164: still could not bind()
https-portal_1  | nginx: [emerg] still could not bind()
https-portal_1  | [cont-finish.d] executing container finish scripts...
https-portal_1  | [cont-finish.d] done.
https-portal_1  | [s6-finish] syncing disks.
https-portal_1  | [s6-finish] sending all processes the TERM signal.
```

**Comment by SteveLTN** [comment]
This is a typical error if your DNS is not ready. Can you verify that if you do

`nslookup git.yourdomain.co`?

you'll see the DNS set up correctly?

**Comment by sbehrends** [comment]
Yes. The DNS is woking as expected. Using other ports I get into the
server. I used a A record to the IP of the server. SSH to the domain is
actually working.

**Comment by sbehrends** [comment]
One detail that may help is that using very it In the terminal works as
expected. Generates and store keys.

Is there any verbose mode?

**Comment by SteveLTN** [comment]
Is it possible that this composition didn't get access to Port 80? Nginx also complains that 80 is taken ... Maybe your other containers in the same compose file?

**Comment by sbehrends** [comment]
This is all logs I get

docker-compose run after clean everything

before run:
```
netstat -tulpn | grep :80
tcp        0      0 0.0.0.0:8050            0.0.0.0:*               LISTEN      928/nginx
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      1594/python
```

running
```
docker-compose rm
Going to remove proxy_https-portal_1
Are you sure? [yN] y
Removing proxy_https-portal_1 ... done
root@alfred ~/proxy # docker-compose up
Creating proxy_https-portal_1
Attaching to proxy_https-portal_1
https-portal_1  | [fix-attrs.d] applying owners & permissions fixes...
https-portal_1  | [fix-attrs.d] 00-runscripts: applying...
https-portal_1  | [fix-attrs.d] 00-runscripts: exited 0.
https-portal_1  | [fix-attrs.d] done.
https-portal_1  | [cont-init.d] executing container initialization scripts...
https-portal_1  | [cont-init.d] 00-setup: executing...
https-portal_1  | Generating DH parameters, 2048 bit long safe prime, generator 2
https-portal_1  | This is going to take a long time
https-portal_1  | ..........................................................................................+............................................+...........................................................................................+............................................................................................................................+.................................................+..........................................................+...................................................................................................................................................................................................................................................................................................................+.......................................+................+.............................................................................................................................................................................................................................................................+..+........................................................................................................................................+..................................+.........+....................................+........................................................................................................................................................................................................+...................+...............................+..........................+.....................................................+............+........................................................................................................................+................................................................................................................................................................+....................................................................................................................+....................................................................................................................................................................................................................+........................................................................................................................................................................................................................................................................................+....................................................................+........................................................................................................+........................................................................................................................................................................................................................+..............................+................................................................................................................................................................................................................+.....................................................................................................................................+..............................................................................................................+......................................................................................................................................................................................................................................................................................+..............................+..............+..................................................................+..............+...+......................................................................................+................................+...........+.....................................................................................................................................................................................................+.......................................+............................................................................................................................................................................................................................................................................................................................+............................................................................................................................................................................................+..........................+.............................................................................................................................................................................................................................................................................................................................................................................+.................................+....................................................................................................................................................................................................................................................................................................................+...................+......................+............................................+..+...................+.......................................................+......................................................................................................................................................+..+.......................................................................................................................................+...................................+........................................................................................................................................................................................+............................................................................................................................+....................................................................................................................................................................................+.....................................................................+...........................................................................................................................................................................+.+..............................+....................................................................................................+...........................+......................................................................................................................................................................................................+............................................................................................................................+..............................................................................................................+.................+....................................................................................+......+.......+.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................+...............................................+..................+.........................................................................................................................................+..........................................+............................................+.......................................................................................................................................................................................................................................+............................................................................+................................................................................................................................................................................................................................................................................................+................................................................................................................+..........+.....................................................................+......................................................................................+.....+...............................................................................................................................................................................................................................................................................................................................................+..............................................................................................................................................................................................................................................................................................................................................+................+.........................................................................................................................................................................+.........................................+....................+.......+........................................................+.....................................................................+............+......................+........................................................................................................................................+........................................................+......................................................................................................................+...................................................................................................+.............................................+..............................................................+........+..............................................................................................................................................++*++*
https-portal_1  | Generating RSA private key, 4096 bit long modulus
https-portal_1  | .......................................++
https-portal_1  | ...................................................................................................................++
https-portal_1  | e is 65537 (0x10001)
https-portal_1  | 2016/11/02 17:43:00 [notice] 125#125: signal process started
https-portal_1  | Generating RSA private key, 2048 bit long modulus
https-portal_1  | .....................+++
https-portal_1  | ....+++
https-portal_1  | e is 65537 (0x10001)
https-portal_1  | Signing certificates from https://acme-v01.api.letsencrypt.org ...
https-portal_1  | Parsing account key...
https-portal_1  | Parsing CSR...
https-portal_1  | Registering account...
https-portal_1  | Registered!
https-portal_1  | Verifying git.mydomain.co...
https-portal_1  | /opt/certs_manager/lib/acme.rb:28:in `system': execution expired (Timeout::Error)
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:28:in `block in le_sign'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
https-portal_1  |   from /usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:16:in `le_sign'
https-portal_1  |   from /opt/certs_manager/lib/acme.rb:9:in `sign'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:60:in `block in ensure_signed'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:53:in `each'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:53:in `ensure_signed'
https-portal_1  |   from /opt/certs_manager/certs_manager.rb:19:in `setup'
https-portal_1  |   from /etc/cont-init.d/00-setup:4:in `<main>'
https-portal_1  | ================================================================================
https-portal_1  | Failed to sign git.mydomain.co, is DNS set up properly?
https-portal_1  | ================================================================================
https-portal_1  | [cont-init.d] 00-setup: exited 1.
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: executing...
https-portal_1  | [cont-init.d] 10-set-docker-gen-status: exited 0.
https-portal_1  | [cont-init.d] done.
https-portal_1  | [services.d] starting services
https-portal_1  | [services.d] done.
https-portal_1  | Starting crond ...
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use)
https-portal_1  | 2016/11/02 17:43:30 [emerg] 166#166: still could not bind()
https-portal_1  | nginx: [emerg] still could not bind()
https-portal_1  | [cont-finish.d] executing container finish scripts...
https-portal_1  | [cont-finish.d] done.
https-portal_1  | [s6-finish] syncing disks.
https-portal_1  | [s6-finish] sending all processes the TERM signal.
https-portal_1  | [s6-finish] sending all processes the KILL signal and exiting.
proxy_https-portal_1 exited with code 0
```

while running
```
netstat -tulpn | grep :80
tcp        0      0 0.0.0.0:8050            0.0.0.0:*               LISTEN      928/nginx
tcp        0      0 127.0.0.1:8000          0.0.0.0:*               LISTEN      1594/python
tcp6       0      0 :::80                   :::*                    LISTEN      15399/docker-proxy

netstat -tulpn | grep :443
tcp6       0      0 :::443                  :::*                    LISTEN      18103/docker-proxy
```

Got no more ideas :(

**Comment by SteveLTN** [comment]
Have you tried when it's not running?

**Comment by sbehrends** [comment]
Feeling stupid right now... Sorry about this.
Just found out that I had 443 port blocked. Still not sure how it did worked when i was usign local environment :|

Thanks for the support. I think it's a great solution!

**Comment by SteveLTN** [comment]
Hmm, but the the verification of domain ownership is from port 80 ...

**Comment by kaplas** [comment]
@SteveLTN Just for the heads up: I had this very same problem, and I as well solved it by running

```
sudo ufw allow 80
sudo ufw allow 443
```

Don't really know _why_ this was necessary, because I switched to `https-portal` from [`nginx-proxy`](https://github.com/jwilder/nginx-proxy) + companions, and didn't have problems with ports before... I had the impression that Docker would manipulate `iptables` directly, without having to add any `ufw` rules, but for some reason, it was not needed.

**Comment by wolfgang42** [comment]
I add that this occurs when the https-portal container cannot contact *itself,* even when outside services can connect to *it*. In my case NAT weirdness caused the service to appear fine on the host but prevented loopback into the container without extra network configuration.

**Comment by SteveLTN** [comment]
@kaplas Docker will modify ufw, but I don't see why it will block 80 and 433. Can you show me your full config?

@wolfgang42 That's interesting. I'll have a look in Christmas.
